### PR TITLE
Report success of chara_create properly based on chara_place

### LINKED ISSUE #546: Segmentation fault in Chara.create
Environment

* OS version: Linux 4.16.9-1-ARCH
* Elona Foobar verision: `develop`

# Details
Segmentation fault when creating a character.

# How to reproduce
```lua
local Event = Elona.require("Event")
local Chara = Elona.require("Chara")
local Map = Elona.require("Map")
local Iter = Elona.require("Iter")
local Enums = Elona.require("Enums")

local function fill_map()
   for pos in Iter.rectangle_iter(0, 0, Map.width() - 1, Map.height() - 1) do
      if pos.x ~= Chara.player().position.x or pos.y ~= Chara.player().position.y then
         Map.set_tile(pos.x, pos.y, Map.generate_tile(Enums.TileKind.Wall))
      end
   end
end

local function create_chara()
   Chara.create(Map.random_pos(), 3)
end

Event.register(Event.EventKind.MapInitialized, fill_map)
Event.register(Event.EventKind.AllTurnsFinished, create_chara)
```

# Cause
Appears to be caused by a failure to place the character.

### PR DESCRIPTION
**Pull request by Ruin0x11**
# Related Issues

Close #546.

# Summary

Fixes `chara_create()` not returning the proper status value if placing the character fails.

### CODE REVIEW

**Comment by ki-foobar** [comment]
It seems to be a reasonable fix, but I'm worried about side-effect. I investigate more that before merging.

File: character.cpp [hunk 1]
```diff
@@ -1009,21 +1009,21 @@ int chara_get_free_slot_ally()
...
         cdata[rc].state = 0;
-        return;
+        return false;
     }
 
     if (gdata_mount != 0 && gdata_mount == rc)
     {
         cdata[rc].position = cdata[0].position;
-        return;
+        return false;
```
Comment (ki-foobar) [inline character.cpp]: `return true;`?

**Comment by ki-foobar** [comment]
It seems that there is no breaking change as far as I see. If not, please post a new issue.
